version: '3.8'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.frontend
        ports:
            - '4200:4200'
        environment:
            REACT_APP_BACKEND_URL: https://portfolio-api.oplor.me
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.backend
        ports:
            - '8080:8080'
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: 1212312121
            DB_NAME: Portfolio
        depends_on:
            - db

    db:
        image: postgres:13
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1212312121
            POSTGRES_DB: Portfolio
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
